name: Assignment automated tests

on: [push]

jobs:
  our-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Valgrind
        run: |
          sudo apt-get -qq install valgrind
      - name: Compile code
        run: |
          make
      - name: Run Tests
        run: |
          python3 tester.py
